### PR TITLE
Track deliverability readiness and dedicated IP lifecycle

### PR DESCRIPTION
**Pull request by jaeyunha**
## Summary

- Adds tenant/domain-scoped deliverability readiness status for BIMI with DMARC/BIMI TXT evaluation, logo URL, and VMC/CMC metadata hints.
- Adds Apple Branded Mail operator-note/status tracking only; no provider submission flow is claimed or triggered.
- Converts dedicated-IP API/dashboard language to manual lifecycle/audit tracking (`requested`, `provisioned`, `warming`, `active`, `suspended`, `retired`) and removes automatic provider pool create/delete side effects from dedicated-IP CRUD.
- Adds dashboard readiness cards, OpenAPI/docs pages, generated `llms.txt`, migration, unit tests, and real-route Playwright tenant/dashboard proof.

Refs #560

## Validation

- `make check && make test` — passed (TypeCheck, Biome, Vitest: 193 files passed, 1 skipped; 1536 tests passed, 4 skipped).
- `DATABASE_URL=postgresql://opensend:opensend@localhost:55432/opensend BETTER_AUTH_SECRET=... bunx playwright test tests/e2e/deliverability-readiness-api.spec.ts` — passed with one cold Next dev-server retry on the domain dashboard scenario; dedicated-IP lifecycle scenario passed.
- `bun run docs:generate` — regenerated `public/docs/llms.txt` after public docs additions.

## Notes

This is the safe first slice from the controller decision: readiness/status/manual support only. It intentionally does not implement automatic BIMI provisioning, Apple Branded Mail submission, dedicated-IP allocation, or warmup automation.

### CODE REVIEW

**Comment by jaeyunha** [comment]
Codex review note after checking live PR state, changed files, and queue interactions.

Verdict: **conditionally mergeable, but not queue-clean yet**.

The PR checks are green, and I did not find a standalone code blocker. The deliverability route is tenant-scoped, the dedicated-IP lifecycle is manual/status-only as described, and the route proof covers the domain/dashboard and dedicated-IP lifecycle scenarios.

Queue blocker: this PR conflicts with #592 and #594 in `drizzle/meta/_journal.json`. Please land schema PRs in an explicit order and regenerate/rebase the Drizzle journal after each merge before merging the next schema PR.

**Comment by jaeyunha** [comment]
Hermes staging integration hold (2026-06-08T16:55Z): not merged.

Live status: `mergeStateStatus=CLEAN`, checks previously green, but held for dependency/migration ordering rather than force-merging out of order.

Blocker: this PR adds `drizzle/0032_deliverability_readiness.sql` and edits `drizzle/meta/_journal.json`; #592 is the intended foundation but currently collides with existing staging migration ordinal `0031`, and #594 also claims `0032_*`.

Needed fix lane: settle/refresh #592 first or explicitly choose an alternate schema order, then revalidate this PR against the resulting staging migration journal before merge.

**Comment by jaeyunha** [comment]
Refresh complete for PR #593 after staging moved via PR #592.

- Old PR head: `7e119084d862f497f4ba68066fea8090535ef66d`
- New pushed PR head: `7f3d8f086a81883cdbc04d86da9cad62bce39086`
- Current base: `origin/staging` at `52d1ef9601904f426fbf4748979ba0ff8edd629d`
- Merge state after push: `CLEAN`; PR is open and non-draft.

Migration refresh:
- Preserved staging migrations `drizzle/0031_youthful_cerebro.sql` and `drizzle/0032_last_flatman.sql` from PR #592.
- Removed the collided old PR migration `drizzle/0032_deliverability_readiness.sql`.
- Regenerated deliverability readiness as `drizzle/0033_past_anita_blake.sql` with `drizzle/meta/0033_snapshot.json`.
- `drizzle/meta/_journal.json` is ordered with `0031_youthful_cerebro` -> `0032_last_flatman` -> `0033_past_anita_blake`.
- While regenerating, I also kept `webhook_deliveries.status` on staging's `pending` default so the refreshed migration only changes deliverability/dedicated-IP surfaces.

Validation evidence:
- `bun install --ignore-scripts` — no dependency changes.
- `bun run db:generate` — generated `0033_past_anita_blake`; rerun was a no-op (`No schema changes, nothing to migrate`).
- Exact conflict marker scan — none.
- Unmerged path scan — none.
- `git diff --check origin/staging..HEAD` — clean.
- Focused Vitest: `bunx vitest run tests/bimi-readiness.test.ts tests/dedicated-ip-plan-gating.test.ts tests/dedicated-ip-pool-repo.test.ts tests/domain-detail-page.test.tsx` — 4 files / 23 tests passed.
- Playwright/API proof with `.env` loaded: `bunx playwright test tests/e2e/deliverability-readiness-api.spec.ts` — 2 tests passed.
- Full local validation: `make check && make test` — typecheck passed, Biome passed, Vitest 205 files / 1656 tests passed, 3 integration files skipped by existing test gates.
- Fresh current-head GitHub checks for `7f3d8f0`: Typecheck, Lint, Unit tests, JVM SDK tests, PHP SDK tests, Onboarding acceptance, Draft Check, and PR Size Label all passed; PR Base Guidance skipped.

Caveats:
- I did not merge the PR and did not close issue #560.
- Local `db:push` hit Drizzle's interactive rename prompt because the local database has an empty Drizzle migration ledger while already containing newer tables; I stopped that path rather than approving broad schema reconciliation. The focused Playwright proof still ran successfully against the local schema after confirming the required deliverability/workspace columns existed.
